### ISSUE TITLE
Random code can cause an exception

### ISSUE THREAD

**Issue by ghandhikus** [samsartor/JFlick#2]
```
java -jar jflick.jar -F "]---"
Exception in thread "main" java.util.NoSuchElementException
        at java.util.ArrayDeque.removeFirst(Unknown Source)
        at java.util.ArrayDeque.pop(Unknown Source)
        at net.eekysam.jflick.ProgramReader.updateLocs(ProgramReader.java:239)
        at net.eekysam.jflick.ProgramReader.read(ProgramReader.java:59)
        at net.eekysam.jflick.Program.<init>(Program.java:29)
        at net.eekysam.jflick.Program.<init>(Program.java:23)
        at net.eekysam.jflick.Main.main(Main.java:178)
Press any key to continue . . .
```

**Comment by ghandhikus** [comment]
A little more information

```
java.util.NoSuchElementException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
    at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
    at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
    at org.jenetics.internal.util.Concurrency$ForkJoinPoolConcurrency.close(Concurrency.java:119)
    at org.jenetics.engine.Engine.evaluate(Engine.java:421)
    at org.jenetics.engine.Engine.evolve(Engine.java:257)
    at org.jenetics.engine.EvolutionSpliterator.tryAdvance(EvolutionSpliterator.java:68)
    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at com.clockwise.genetics.App.main(App.java:83)
Caused by: java.util.NoSuchElementException
    at java.util.ArrayDeque.removeFirst(ArrayDeque.java:280)
    at java.util.ArrayDeque.pop(ArrayDeque.java:517)
    at net.eekysam.jflick.ProgramReader.updateLocs(ProgramReader.java:239)
    at net.eekysam.jflick.ProgramReader.read(ProgramReader.java:59)
    at net.eekysam.jflick.Program.<init>(Program.java:29)
    at net.eekysam.jflick.Program.<init>(Program.java:23)
    at net.eekysam.jflick.Main.main(Main.java:178)
    at com.clockwise.genetics.App.eval(App.java:57)
    at org.jenetics.Phenotype.eval(Phenotype.java:143)
    at org.jenetics.Phenotype.evaluate(Phenotype.java:136)
    at org.jenetics.Phenotype.run(Phenotype.java:156)
    at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:73)
    at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
    at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:759)
    at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:77)
    at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
    at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:759)
    at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:77)
    at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
    at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:759)
    at org.jenetics.internal.util.RunnablesAction.compute(RunnablesAction.java:77)
    at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```
